language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UYXyl1wEK9BOWwiFj4tDXGSARjZK42EBLmZA2JJmOcYEPbnS+uDG8svgE84SGTyHGb/UiWdkAGa6gtCZymG/cm7GAGtZq7OvVMExW58GytJUw3HqYQ3MrUY+KxbeyelApXU8RYoeFx9pMt6katgGkGZjqnnIkvQQVPv80mmtr0NsV69thw3vWyXWbVvBFf36RkyIoUPtNvxyukDrYzhw9b2lsabPGrT8VBw5v9YRU/v9oPnASFPdZjMw23PD3FsiWIMm0P/Nlzi5TRDjAUa6GmtJJmqEK6aZZSjQMVVZMhxhHNIx0FQGB1Vb6iIzuasupDRPVJ00aw8092wuzgfRZEVW953Dc/QC8ij9wWcRIwhXC2tYOfcKv2U/0FXl9SxyABCtt23+hLB1kHz6u8R+uqKMZ/5qsZZYwpquzsZDjHlXY7jOsKThMAV7TEB03yUrQw55jbrLckYHNKMQlY7dWOgSo/SXWWRZ6P90SoWeqk53CkNNAXC7wWm/0qAt9S0/CGQu3VPplZM4phmeY3VdJaSandsnFhbwgJEXAluViYSRUFE6hUX+o+vlJ7N5MLVhnb8EWl7RvwFFiLrygTYOAM+fvcCWvBSDbBz6EJ7nHZpw/NRdkxVUDLhliVm2pDu7DWGnFQ2mFu0AE96VuWoju8afpg2dTERfghLI4ygOlPc=
  file:
    - 'quotation.js'
    - 'quotation.min.js'
  on:
    tags: true
