language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: w6rf4RWLh/992zFv2EsSjDgxx80LeMu0RBdAOr3agHO8APbeyjZxtKt6qZuG0GHXT2yME54CZz2dIvolv4w+mw8d5epTMFAFoBNQFqnWRTCMxi7uVNKzidV+axGbS9byyoUYzU4H3gFz9+6pEjSwIqb2qWnkjfr0XF/eD0VF5zewEkZoLnjtc/dU756hKbzJewE777pJPRv3+uZsx3DTs8UhDn/MzD5nA+ArCRtZCyAfyr3zQsIToS8XG9+jj1pUKY/MrKTvnPHxMt7WkM+xNz0Vb3O73Rkkcyjz0Toz4zP/Gb6jmyxfMmgMvP4iYvxSC+21XTigtC0jiKxx9WUlSEV75wSrl4kPzIQHbCS6TbN65WyiD3Jo193yKn9cSw2GN8RBWjeQeWQbmrskazO0u3F35g9+LHmPdjKuiWd9EUp8YZ42vrt9FfjC090KznFJ6LUP3sjhP1ICqeCuRVFVrmywkT9TIcmpvv6cpGgGek+GH2Sonw90i71uY2jIBMizF6bIeSE2rtdVxrkchIAm6JYQWq6WbJrHZhigGXFh25bq1ojGljPFLyPZ1Z9lti3Eg1iNBeVBQIEBrVfu+RQaJ/xa/Ok1hgW2SEDYLI1VoZzlDN96PwDdERkKmfxOyaCyDNynpgV1tKT7YUNJpdGRFmBo67UuozD/OXvVY95o/q4=
  file:
    - "quotation.js"
    - "quotation.min.js"
  on:
    tags: true
